language: node_js
node_js:
  - "stable"
os:
  - linux
sudo: required
addons:
  chrome: stable
  firefox: latest
env:
  global:
    - MOZ_HEADLESS=1
cache:
  directories:
    - node_modules
script:
  - npm install
  - node_modules/karma/bin/karma start karma.conf.js --single-run
after_script: node_modules/grunt-cli/bin/grunt coverage
notifications:
  slack: mtr-design:8Hj8yAQDcHqPZKpylxbalk9K